#!/bin/zsh

#TARGETS名称
target_name="HuaRongDao"

#工程路径
project_path="/Users/ccf/iphone/HuaRongDao"

#build文件夹路径
build_path=${project_path}/build


#编译工程
cd $project_path
xcodebuild -configuration DailyBuild -target "$target_name"

#打包
cd $build_path
mkdir -p ipa/Payload
cp -r ./DailyBuild-iphoneos/${target_name}.app ./ipa/Payload/
cd ipa
zip -r ${target_name}.ipa *
rm -rf Payload

